export const data = [
  {
    name: "iPhone 14 Pro",
    category: "Smartphone",
    description:
      "Apple's latest flagship smartphone with advanced camera and display technology.",
    features: [
      "6.7-inch Super Retina XDR display",
      "Triple-camera system with LiDAR scanner",
      "5G connectivity",
      "A16 Bionic chip",
      "ProMotion technology",
      "iOS 16",
    ],
    price: "$1099",
    colors: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    rating: 4,
    releasedDate: "2022-09-30",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/717trh2j6CL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41+DC2aGiuL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg",
    ],
    id: "1",
  },
  {
    name: "iPhone 13 Mini",
    category: "Smartphone",
    description:
      "Compact flagship iPhone with powerful features in a small size.",
    features: [
      "5.4-inch Super Retina XDR display",
      "Dual-camera system",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$699",
    colors: ["Pink", "Blue", "Midnight", "Starlight", "Product(RED)"],
    rating: 4,
    releasedDate: "2021-09-24",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/51yG1FjZVYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Z4qLSOGhL._AC_SL1200_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-mini-01.jpg",
    ],
    id: "2",
  },
  {
    name: "iPhone SE (2022)",
    category: "Smartphone",
    description: "Affordable iPhone with A15 chip and 5G capability.",
    features: [
      "4.7-inch Retina HD display",
      "Single 12MP wide camera",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$429",
    colors: ["Midnight", "Starlight", "Product(RED)"],
    rating: 3.5,
    releasedDate: "2022-03-18",
    brand: "Apple",
    images: [
      "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022.jpg",
      "https://cdn.shortpixel.ai/spai/w_375+q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022-colors.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/apple-iphone-se-2020/lifestyle/-1024w2/gsmarena_009.jpg",
    ],
    id: "3",
  },
  {
    name: "iPhone 12",
    category: "Smartphone",
    description: "Powerful and iconic smartphone with impressive technology.",
    features: [
      "6.1-inch Super Retina XDR display",
      "Dual-camera system",
      "A14 Bionic chip",
      "iOS 14",
      "5G connectivity",
    ],
    price: "$799",
    colors: ["Black", "White", "Red", "Green", "Blue"],
    rating: 4.5,
    releasedDate: "2020-10-23",
    brand: "Apple",
    images: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg",
      "https://m.media-amazon.com/images/I/71UlOmYIClL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg",
    ],
    id: "4",
  },
  {
    name: "iPhone 11",
    category: "Smartphone",
    description: "Affordable yet powerful iPhone great for photography.",
    features: [
      "6.1-inch Liquid Retina HD display",
      "Dual-camera system",
      "A13 Bionic chip",
      "iOS 13",
      "4G LTE connectivity",
    ],
    price: "$499",
    colors: ["Purple", "Yellow", "Green", "Black", "White", "Red"],
    rating: 4,
    releasedDate: "2019-09-20",
    brand: "Apple",
    images: [
      "https://dubaiphone.s3.eu-central-1.amazonaws.com/dp-prod/wp-content/uploads/2023/11/Apple-iPhone-11-With-FaceTime-128GB-4GB-RAM-4G_2158_2.jpeg",
      "https://dubaiphone.s3.eu-central-1.amazonaws.com/dp-prod/wp-content/uploads/2023/11/2651.webp",
      "https://dubaiphone.s3.eu-central-1.amazonaws.com/dp-prod/wp-content/uploads/2023/11/5649-768x768.webp",
    ],
    id: "5",
  },
  {
    name: "Samsung Galaxy S23 Ultra",
    category: "Smartphone",
    description: "High-end smartphone with advanced photography capabilities.",
    features: [
      "6.8-inch Edge QHD+ display",
      "108MP main camera with 100x Space Zoom",
      "Snapdragon 8 Gen 2 for Galaxy",
      "5G connectivity",
      "One UI 5.1",
      "5000mAh battery",
    ],
    price: "$1199",
    colors: ["Phantom Black", "Green", "Cream", "Lavender"],
    rating: 5,
    releasedDate: "2023-02-17",
    brand: "Samsung",
    images: [
      "https://m.media-amazon.com/images/I/713icYPjIZL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/710ySJlVgeL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/710qvSo1rRL._AC_SL1500_.jpg",
    ],
    id: "6",
  },
  {
    name: "Samsung Galaxy Z Flip4",
    category: "Smartphone",
    description: "Innovative foldable smartphone that fits into any pocket.",
    features: [
      "6.7-inch Foldable Dynamic AMOLED 2X",
      "12MP dual rear cameras",
      "Snapdragon 8+ Gen 1",
      "3700mAh dual battery",
      "One UI 4.1.1 based on Android 12L",
    ],
    price: "$999",
    colors: ["Bora Purple", "Graphite", "Pink Gold", "Blue"],
    rating: 4.5,
    releasedDate: "2022-08-25",
    brand: "Samsung",
    images: [
      "https://m.media-amazon.com/images/I/618RSkYxa+L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71YrR1e5uOL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/519GFtQ58OL._AC_SL1019_.jpg",
    ],
    id: "7",
  },
  {
    name: "Samsung Galaxy Note 20 Ultra",
    category: "Smartphone",
    description: "High-performance smartphone with S-Pen for productivity.",
    features: [
      "6.9-inch Edge Quad HD+ display",
      "108MP triple rear camera setup",
      "Snapdragon 865+",
      "5G connectivity",
      "4500mAh battery",
    ],

    price: "$1299",
    colors: ["Mystic Bronze", "Mystic Black", "Mystic White"],
    rating: 4.5,
    releasedDate: "2020-08-21",
    brand: "Samsung",
    images: [
      "https://m.media-amazon.com/images/I/61kX8S4MBuL._AC_SL1001_.jpg",
      "https://m.media-amazon.com/images/I/51toSWDgELL._AC_.jpg",
      "https://m.media-amazon.com/images/I/41AWmW5e3jL._AC_.jpg",
    ],
    id: "8",
  },
  {
    name: "Samsung Galaxy A54 5G",
    category: "Smartphone",
    description: "Mid-range smartphone with a focus on camera and display.",
    features: [
      "6.5-inch Super AMOLED display",
      "Quad-camera system",
      "Exynos 1280",
      "5G connectivity",
      "4500mAh battery",
    ],
    price: "$449",
    colors: [
      "Awesome Black",
      "Awesome White",
      "Awesome Violet",
      "Awesome Blue",
    ],
    rating: 4,
    releasedDate: "2022-03-17",
    brand: "Samsung",
    images: [
      "https://m.media-amazon.com/images/I/614qsXB-XUL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/515EFhbeHUL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61XYO1T7QTL._AC_SL1477_.jpg",
      "",
    ],
    id: "9",
  },
  {
    name: "Sony Xperia 1 IV",
    category: "Smartphone",
    description: "Smartphone designed for photography and video enthusiasts.",
    features: [
      "6.5-inch 4K HDR OLED display",
      "Continuous optical zoom",
      "Snapdragon 8 Gen 1",
      "5G connectivity",
      "5000mAh battery",
    ],
    price: "$1399",
    colors: ["Black", "Purple", "White"],
    rating: 4,
    releasedDate: "2022-06-01",
    brand: "Sony",
    images: [
      "https://m.media-amazon.com/images/I/81iDW4Xo61L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81ETtg3+nXL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81m6bpYAMzL._AC_SL1500_.jpg",
    ],
    id: "10",
  },
  {
    name: "Sony Xperia 5 III",
    category: "Smartphone",
    description:
      "Compact powerhouse smartphone with advanced camera capabilities.",
    features: [
      "6.1-inch 21:9 CinemaWide display",
      "Triple-lens camera system with ZEISS optics",
      "Snapdragon 888",
      "5G connectivity",
      "4500mAh battery",
    ],
    price: "$999",
    colors: ["Black", "Green"],
    rating: 4.5,
    releasedDate: "2021-08-19",
    brand: "Sony",
    images: [
      "https://m.media-amazon.com/images/I/61P+Ze-VVML._AC_SL1096_.jpg",
      "https://m.media-amazon.com/images/I/51yFDADcdQL._AC_SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61zoHzHZ1aL._AC_SL1065_.jpg",
    ],
    id: "11",
  },
  {
    name: "Sony Xperia PRO-I",
    category: "Smartphone",
    description:
      "Professional-grade smartphone with a high-resolution camera and 5G capability.",
    features: [
      "6.5-inch 4K HDR OLED display",
      "Triple-lens ZEISS camera system",
      "Snapdragon 888",
      "5G connectivity",
      "4500mAh battery",
    ],
    price: "$1899",
    colors: ["Black"],
    rating: 4,
    releasedDate: "2021-10-22",
    brand: "Sony",
    images: [
      "https://fdn2.gsmarena.com/vv/pics/sony/sony-xperia-pro-i-1.jpg",
      "https://fdn2.gsmarena.com/vv/pics/sony/sony-xperia-pro-i-2.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/21/sony-xperia-pro-i/preview/lifestyle/-1024w2/gsmarena_002.jpg",
    ],
    id: "12",
  },
  {
    name: "Sony Xperia 10 IV",
    category: "Smartphone",
    description:
      "Mid-range smartphone with a focus on multimedia and performance.",
    features: [
      "6.0-inch Full HD+ OLED display",
      "Triple-lens camera system",
      "Snapdragon 690",
      "5G connectivity",
      "4500mAh battery",
    ],
    price: "$499",
    colors: ["Black", "Blue"],
    rating: 4,
    releasedDate: "2022-04-14",
    brand: "Sony",
    images: [
      "https://fdn.gsmarena.com/imgroot/reviews/22/sony-xperia-10-iv/lifestyle/-1024w2/gsmarena_003.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/sony-xperia-10-iv/lifestyle/-1024w2/gsmarena_004.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/sony-xperia-10-iv/lifestyle/-1024w2/gsmarena_002.jpg",
    ],
    id: "13",
  },
  {
    name: "LG Velvet",
    category: "Smartphone",
    description:
      "Stylish smartphone with a unique design and dual-screen support.",
    features: [
      "6.8-inch P-OLED display",
      "Triple rear cameras",
      "Snapdragon 765G",
      "5G connectivity",
      "4300mAh battery",
    ],
    price: "$599",
    colors: ["Aurora Green", "Sunset", "Black", "White"],
    rating: 3.5,
    releasedDate: "2020-05-15",
    brand: "LG",
    images: [
      "https://fdn.gsmarena.com/imgroot/reviews/20/lg-velvet/review24/lifestyle/-1024w2/gsmarena_018.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/lg-velvet/review24/lifestyle/-1024w2/gsmarena_022.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/lg-velvet/review24/lifestyle/-1024w2/gsmarena_023.jpg",
      "",
    ],
    id: "14",
  },
  {
    name: "LG Wing",
    category: "Smartphone",
    description:
      "Innovative dual-screen smartphone with swivel mechanism for multitasking.",
    features: [
      "6.8-inch P-OLED main display",
      "4-inch G-OLED secondary display",
      "64MP triple rear camera setup",
      "Snapdragon 765G",
      "5G connectivity",
      "4000mAh battery",
    ],
    price: "$999",
    colors: ["Aurora Gray", "Illusion Sky"],
    rating: 4,
    releasedDate: "2020-10-05",
    brand: "LG",
    images: [
      "https://www.lg.com/us/mobile-phones/wing-5g/assets/images/product/hero-medium.jpg",
      "https://www.lg.com/us/mobile-phones/wing-5g/assets/images/product/4-medium.jpg",
      "https://www.lg.com/us/mobile-phones/wing-5g/assets/images/product/34-xlarge.jpg",
    ],
    id: "15",
  },
  {
    name: "LG G8 ThinQ",
    category: "Smartphone",
    description:
      "Flagship smartphone with advanced audio features and AI capabilities.",
    features: [
      "6.1-inch OLED display",
      "Dual-lens rear camera",
      "Snapdragon 855",
      "4G LTE connectivity",
      "3500mAh battery",
    ],
    price: "$849",
    colors: ["Aurora Black", "Moroccan Blue"],
    rating: 4,
    releasedDate: "2019-04-11",
    brand: "LG",
    images: [
      "https://fdn2.gsmarena.com/vv/pics/lg/lg-g8s-thinq-1.jpg",
      "https://fdn2.gsmarena.com/vv/pics/lg/lg-g8s-thinq-3.jpg",
      "https://fdn2.gsmarena.com/vv/pics/lg/lg-g8s-thinq-4.jpg",
    ],
    id: "16",
  },
  {
    name: "LG K92 5G",
    category: "Smartphone",
    description:
      "Affordable 5G smartphone with a large display and quad-camera system.",
    features: [
      "6.7-inch Full HD+ display",
      "Quad rear cameras",
      "Snapdragon 690",
      "5G connectivity",
      "4000mAh battery",
    ],
    price: "$359",
    colors: ["Titan Gray"],
    rating: 3.5,
    releasedDate: "2020-11-06",
    brand: "LG",
    images: [
      "https://www.lg.com/content/dam/channel/wcms/ca_en/images/cell-phones/lmg820um2_acanbk_enci_ca_en_c/gallery/large01_v1.jpg",
      "https://www.lg.com/content/dam/channel/wcms/ca_en/images/cell-phones/lmg820um2_acanbk_enci_ca_en_c/gallery/zoom-05_v1.jpg",
      "https://www.lg.com/content/dam/channel/wcms/ca_en/images/cell-phones/lmg820um2_acanbk_enci_ca_en_c/md06093537/gallery/large02.jpg",
    ],
    id: "17",
  },
  {
    name: "Huawei P50 Pro",
    category: "Smartphone",
    description: "High-end smartphone with pioneering photography technology.",
    features: [
      "6.6-inch OLED display",
      "Quad rear camera setup",
      "Kirin 9000",
      "HarmonyOS",
      "4360mAh battery",
    ],
    price: "$1200",
    colors: ["Cocoa Gold", "Golden Black", "Pearl White"],
    rating: 4.5,
    releasedDate: "2021-08-12",
    brand: "Huawei Technologies Co., Ltd.",
    images: [
      "https://fdn.gsmarena.com/imgroot/reviews/22/huawei-p50-pro/lifestyle/-1024w2/gsmarena_006.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/huawei-p50-pro/lifestyle/-1024w2/gsmarena_007.jpg",
      "https://fdn2.gsmarena.com/vv/pics/huawei/huawei-p50-pro-0.jpg",
    ],
    id: "18",
  },
  {
    name: "Huawei Mate 40 Pro",
    category: "Smartphone",
    description: "Powerful flagship smartphone with advanced AI capabilities.",
    features: [
      "6.76-inch OLED display",
      "Triple-lens Leica camera system",
      "Kirin 9000",
      "EMUI 11",
      "4400mAh battery",
    ],
    price: "$1199",
    colors: ["Mystic Silver", "White", "Black", "Green", "Yellow"],
    rating: 4,
    releasedDate: "2020-10-22",
    brand: "Huawei Technologies Co., Ltd.",
    images: [
      "https://fdn.gsmarena.com/imgroot/reviews/20/huawei-mate-40-pro/review-22/lifestyle/-1024w2/gsmarena_002.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/huawei-mate-40-pro/review-22/lifestyle/-1024w2/gsmarena_013.jpg",
      "https://fdn2.gsmarena.com/vv/pics/huawei/huawei-mate40-pro-1.jpg",
    ],
    id: "19",
  },
  {
    name: "Huawei nova 9",
    category: "Smartphone",
    description: "Mid-range smartphone with a focus on design and photography.",
    features: [
      "6.57-inch OLED display",
      "Quad rear camera setup",
      "Kirin 990E",
      "EMUI 12",
      "4300mAh battery",
    ],
    price: "$499",
    colors: ["Crystal Blue", "Crystal Pink", "Midnight Black", "Honey Red"],
    rating: 4,
    releasedDate: "2021-09-23",
    brand: "Huawei Technologies Co., Ltd.",
    images: [
      "https://fdn.gsmarena.com/imgroot/reviews/21/huawei-nova-9/lifestyle/-1024w2/gsmarena_004.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/21/huawei-nova-9/lifestyle/-1024w2/gsmarena_005.jpg",
      "https://fdn2.gsmarena.com/vv/pics/huawei/huawei-nova-9-5g-1.jpg",
    ],
    id: "20",
  },
  {
    name: "Lenovo IdeaPad 1",
    category: "Laptop",
    description:
      "1x USB 2.0 1x USB 3.2 Gen 1 1x USB-C® 3.2 Gen 1 (support data transfer only) 1x HDMI® 1.4b 1x Headphone / microphone combo jack (3.5mm) 1x Card reader 1x Power connector",
    features: [
      "Processor Intel® Core™ i3-1215U",
      "Processor Generation 12th generation",
      "Video graphics Intel® UHD Graphics",
      "RAM 4GB Soldered DDR4-3200",
      "Display 15.6 HD (1366x768) TN 220nits Anti-glare",
      "Battery Integrated 42Wh",
    ],
    price: "L.E 16499",
    colors: ["Black", "Grey", "Silver"],
    rating: 4,
    releasedDate: "2022-09-30",
    brand: "Lenovo",
    images: [
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl215-1-2bn_1.jpg",
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl274-2-2b-min_2_1.jpg",
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl274-3-2b-min_2_1.jpg",
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl274-4-2b-min_2_1.jpg",
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl274-5-2b-min_2_1.jpg",
    ],
    id: "21",
  },
  {
    name: "ThinkPad X1 Carbon Gen 11 (14” Intel) Laptop",
    category: "Laptop",
    description:
      "Lenovo ThinkPad X1 Carbon Gen 11 21HM002DUS Black Laptop, i7-1355U, 16GB, 512GB PCIe SSD, 14.0 IPS Touch Wide UXGA (1920x1200), Intel Iris Xe, Windows 11 Pro",
    features: [
      "Certified Intel® Evo™ with up to 13th Gen Intel® Core™ vPro® CPU",
      "Ultralight starting weight of just 1.12kg / 2.48lb",
      "Super-responsive with twice the memory as previous gen",
      "Optimized thermals with dual fan & rear venting",
      "4 x 360-degree mics with AI-based noise cancellation & Dolby Voice® ",
      "Zoom certified for collaboration, sales, customer support, & development",
    ],
    price: "L.E 36499",
    colors: ["Black", "Dark Blue", "Silver"],
    rating: 4,
    releasedDate: "2025-09-30",
    brand: "Lenovo",
    images: [
      "https://m.media-amazon.com/images/I/61QQ0K0UPXL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61XTNmdEHRL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/619BIQJZxqL._AC_SX679_.jpg0",
      "https://m.media-amazon.com/images/I/71nSFBZbpqL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/719NJLFPtyL._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/71KnPb-njwL._AC_SY450_.jpg",
    ],
    id: "22",
  },
  {
    name: "Lenovo Yoga Slim 7",
    category: "Laptop",
    description:
      "Lenovo Yoga Slim 7, AMD Ryzen 7 5700U Processor, 16GB DDR4, 1TB SSD, AMD Radeon Graphics, 14 Inch QHD (2560x1440) IPS 400nits Glossy, Windows 11, Slate Grey, 1.34Kg, 82A3004SAK",
    features: [
      "Processor AMD Ryzen 7 5700U Processor",
      "RAM 16GB DDR4",
      "Storage 1TB SSD",
      "Graphics AMD Radeon Graphics",
      "Display 14 Inch QHD (2560x1440) IPS 400nits Glossy",
      "Operating System Windows 11",
    ],
    price: "L.E 22999",
    colors: ["Slate Grey"],
    rating: 5,
    releasedDate: "2023-11-15",
    brand: "Lenovo",
    images: [
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl379.png",
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl379--2.png",
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl379--3.png",
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl379--4.png",
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl379--5.png",
      "https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/z/l/zl379--6.png",
    ],
    id: "23",
  },
  {
    name: "Dell Inspiron 15",
    category: "Laptop",
    description:
      "Dell Inspiron 15, Intel Core i5-11300H, 8GB DDR4, 512GB SSD, NVIDIA GeForce MX450, 15.6 Inch FHD (1920x1080) Anti-Glare LED Backlight Non-Touch Narrow Border WVA Display, Windows 11, D560524WIN9S",
    features: [
      "Processor Intel Core i5-11300H",
      "RAM 8GB DDR4",
      "Storage 512GB SSD",
      "Graphics NVIDIA GeForce MX450",
      "Display 15.6 Inch FHD (1920x1080) Anti-Glare LED Backlight Non-Touch Narrow Border WVA Display",
      "Operating System Windows 11",
    ],
    price: "L.E 22999",
    colors: ["Black"],
    rating: 4,
    releasedDate: "2023-12-01",
    brand: "Dell",
    images: [
      "https://m.media-amazon.com/images/I/71lsq9TesJL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71SUsef4s8L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61XJV3b6ZgL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51VYkhONkQL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/518DkDdkeBL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41K+EQdHUjL._AC_SX679_.jpg",
    ],
    id: "24",
  },
  {
    name: "HP Pavilion x360",
    category: "Laptop",
    description:
      "HP Pavilion x360 14-dw1007ne, Intel Core i7-1165G7, 16GB DDR4, 1TB SSD, Intel Iris Xe Graphics, 14 Inch FHD IPS BrightView micro-edge WLED-backlit Touch Display, Windows 11, 2Y4R9EA",
    features: [
      "Processor Intel Core i7-1165G7",
      "RAM 16GB DDR4",
      "Storage 1TB SSD",
      "Graphics Intel Iris Xe Graphics",
      "Display 14 Inch FHD IPS BrightView micro-edge WLED-backlit Touch Display",
      "Operating System Windows 11",
    ],
    price: "L.E 29999",
    colors: ["Silver"],
    rating: 4,
    releasedDate: "2023-10-15",
    brand: "HP",
    images: [
      "https://m.media-amazon.com/images/I/81BLK5ExrbL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/7134Wqcu-qL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81fE0LSGELL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71e7B5MKBIL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71Dmy0xE0aL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61ePDMcqgeL._AC_SX679_.jpg",
    ],
    id: "25",
  },
  {
    name: "Acer Aspire 7",
    category: "Laptop",
    description:
      "Acer Aspire 7 A715-42G-R6Z3, AMD Ryzen 5 5500U, 8GB DDR4, 512GB SSD, NVIDIA GeForce GTX 1650, 15.6 Inch FHD (1920x1080) IPS Display, Windows 11, Black, 1 Year Local Warranty",
    features: [
      "Processor AMD Ryzen 5 5500U",
      "RAM 8GB DDR4",
      "Storage 512GB SSD",
      "Graphics NVIDIA GeForce GTX 1650",
      "Display 15.6 Inch FHD (1920x1080) IPS Display",
      "Operating System Windows 11",
    ],
    price: "L.E 18999",
    colors: ["Black"],
    rating: 4,
    releasedDate: "2023-11-01",
    brand: "Acer",
    images: [
      "https://m.media-amazon.com/images/I/71DhkHs4pqL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71vWKn4cCFL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/613UK03N1PL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71YV41Fky7L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51dwDWGHowS._AC_SX679_.jpg",
    ],
    id: "26",
  },
  {
    name: "ASUS ROG Zephyrus G14",
    category: "Laptop",
    description:
      "ASUS ROG Zephyrus G14 GA401QE, AMD Ryzen 9 5900HS, 16GB DDR4, 1TB SSD, NVIDIA GeForce GTX 1650Ti, 14 Inch FHD 120Hz IPS Display, Windows 11, Eclipse Gray, 2 Year Local Warranty",
    features: [
      "Processor AMD Ryzen 9 5900HS",
      "RAM 16GB DDR4",
      "Storage 1TB SSD",
      "Graphics NVIDIA GeForce GTX 1650Ti",
      "Display 14 Inch FHD 120Hz IPS Display",
      "Operating System Windows 11",
    ],
    price: "L.E 31999",
    colors: ["Eclipse Gray"],
    rating: 5,
    releasedDate: "2023-10-15",
    brand: "ASUS",
    images: [
      "https://m.media-amazon.com/images/I/81Ql+nOEynL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81c6-AKtbmL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71B8P-zlcGL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81uNIFnGHvL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81J5BoEtbgL._AC_SX679_.jpg",
    ],
    id: "27",
  },
  {
    name: "ASUS Vivobook",
    category: "Laptop",
    description:
      "MSI GF65 Thin 10UE-240, Intel Core i7-10750H, 16GB DDR4, 512GB SSD, NVIDIA GeForce RTX3060 Max-Q, 15.6 Inch FHD (1920x1080) IPS Display, Windows 11, Black, 1 Year Local Warranty",
    features: [
      "Processor Intel Core i7-10750H",
      "RAM 16GB DDR4",
      "Storage 512GB SSD",
      "Graphics NVIDIA GeForce RTX3060 Max-Q",
      "Display 15.6 Inch FHD (1920x1080) IPS Display",
      "Operating System Windows 11",
    ],
    price: "L.E 29999",
    colors: ["Black"],
    rating: 5,
    releasedDate: "2023-12-01",
    brand: "MSI",
    images: [
      "https://m.media-amazon.com/images/I/61FYc36J93L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71fPuKH1r5L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71x4NyDqLYL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71BnQCuVeBL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71x6yG5-QuL._AC_SX679_.jpg",
    ],
    id: "28",
  },
  {
    name: "Apple MacBook Pro",
    category: "Laptop",
    description:
      "Apple MacBook Pro 14-inch with Apple M1 Pro chip (2021 Model) with 8-core CPU and 14-core GPU, 16GB RAM, 512GB SSD - Space Gray",
    features: [
      "Apple M1 Pro chip with 8-core CPU and 14-core GPU",
      "16GB unified memory",
      "512GB SSD storage",
      "14-inch Liquid Retina XDR display with ProMotion",
      "Operating System macOS Monterey",
    ],
    price: "L.E 44999",
    colors: ["Space Gray"],
    rating: 5,
    releasedDate: "2021-10-26",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/619L9jf3-rL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71u7ZoxwLkL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/919EXGgh2aL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/919EXGgh2aL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71XSEMx26HL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51k92mFqIcL._AC_SX679_.jpg",
    ],
    id: "29",
  },
  {
    name: "Dell Vostro 3520 ",
    category: "Laptop",
    description:
      "Razer Blade 15 Advanced Gaming Laptop 2021: Intel Core i7-11800H 8-Core, NVIDIA GeForce RTX 3080, 15.6” 4K OLED, 16GB RAM, 1TB SSD - CNC Aluminum - Chroma RGB - THX Spatial Audio - Thunderbolt 4 - Windows 11 - Black",
    features: [
      "Intel Core i7-11800H 8-Core",
      "NVIDIA GeForce RTX 3080",
      "15.6” 4K OLED Display",
      "16GB RAM",
      "1TB SSD",
      "THX Spatial Audio",
      "Thunderbolt 4",
      "Operating System Windows 11",
    ],
    price: "L.E 64999",
    colors: ["Black"],
    rating: 5,
    releasedDate: "2021-09-15",
    brand: "Razer",
    images: [
      "https://m.media-amazon.com/images/I/71JPy7gSTyL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71AcUeT6dCL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71+-viLETIL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/918HRPEckUL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81za0uiwWOL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81jfVxV3HNL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61SGSs678qL._AC_SX679_.jpg",
    ],
    id: "30",
  },
  {
    name: "HP Spectre x360",
    category: "Laptop",
    description:
      "HP Spectre x360 Convertible Laptop, Intel Core i7-1165G7, 16GB DDR4, 1TB SSD, NVIDIA GeForce GTX 1650Ti, 15.6 Inch 4K UHD AMOLED Touch Display, Windows 11, Poseidon Blue, 3C7W9EA",
    features: [
      "Processor Intel Core i7-1165G7",
      "RAM 16GB DDR4",
      "Storage 1TB SSD",
      "Graphics NVIDIA GeForce GTX 1650Ti",
      "Display 15.6 Inch 4K UHD AMOLED Touch Display",
      "Operating System Windows 11",
    ],
    price: "L.E 38999",
    colors: ["Poseidon Blue"],
    rating: 4,
    releasedDate: "2023-11-30",
    brand: "HP",
    images: [
      "https://m.media-amazon.com/images/I/81BLK5ExrbL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/7134Wqcu-qL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81fE0LSGELL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71e7B5MKBIL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61ePDMcqgeL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71Dmy0xE0aL._AC_SX679_.jpg",
    ],
    id: "31",
  },
  {
    name: "Microsoft Surface Laptop 4",
    category: "Laptop",
    description:
      "Microsoft Surface Laptop 4, AMD Ryzen 7 4980U, 16GB RAM, 512GB SSD, 15 Inch PixelSense Touch Display, Windows 11, Platinum",
    features: [
      "Processor AMD Ryzen 7 4980U",
      "RAM 16GB",
      "Storage 512GB SSD",
      "Display 15 Inch PixelSense Touch Display",
      "Operating System Windows 11",
    ],
    price: "L.E 32999",
    colors: ["Platinum"],
    rating: 4.5,
    releasedDate: "2023-10-15",
    brand: "Microsoft",
    images: [
      "https://m.media-amazon.com/images/I/71Jv3cG3DDL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71xoIeT2GTL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61+RpPUK2IL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81N6ePutElL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51WxWZJgypL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61YkmCIfbvL._AC_SX679_.jpg",
    ],
    id: "32",
  },
  {
    name: "Samsung Galaxy Book Pro 360",
    category: "Laptop",
    description:
      "Samsung Galaxy Book Pro 360, Intel Core i7-1165G7, 16GB DDR4, 1TB SSD, Intel Iris Xe Graphics, 15.6 Inch FHD Super AMOLED Touch Display, Windows 11, Mystic Navy",
    features: [
      "Processor Intel Core i7-1165G7",
      "RAM 16GB DDR4",
      "Storage 1TB SSD",
      "Graphics Intel Iris Xe Graphics",
      "Display 15.6 Inch FHD Super AMOLED Touch Display",
      "Operating System Windows 11",
    ],
    price: "L.E 34999",
    colors: ["Mystic Navy"],
    rating: 4.5,
    releasedDate: "2023-09-30",
    brand: "Samsung",
    images: [
      "https://m.media-amazon.com/images/I/71ysHVMH4FL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71WBELZFc2L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81tcbvWrf1L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/8104FJFrsSL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61iBY7OynjL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81G3d+N9VgL._AC_SX679_.jpg",
    ],
    id: "33",
  },
  {
    name: "Lenovo Legion 5 Pro",
    category: "Laptop",
    description:
      "Lenovo Legion 5 Pro, AMD Ryzen 9 6900HX, 32GB DDR4, 1TB SSD, NVIDIA GeForce RTX 3070, 16 Inch QHD 165Hz IPS Display, Windows 11, Storm Grey",
    features: [
      "Processor AMD Ryzen 9 6900HX",
      "RAM 32GB DDR4",
      "Storage 1TB SSD",
      "Graphics NVIDIA GeForce RTX 3070",
      "Display 16 Inch QHD 165Hz IPS Display",
      "Operating System Windows 11",
    ],
    price: "L.E 49999",
    colors: ["Storm Grey"],
    rating: 5,
    releasedDate: "2023-11-15",
    brand: "Lenovo",
    images: [
      "https://m.media-amazon.com/images/I/41iIZTU6cRS._AC_.jpg",
      "https://m.media-amazon.com/images/I/31WRkiAH6GS._AC_.jpg",
      "https://m.media-amazon.com/images/I/41Gurcd-nVS._AC_.jpg",
      "https://m.media-amazon.com/images/I/41uD-x8h5NS._AC_.jpg",
      "https://m.media-amazon.com/images/I/21dE9++IQBS._AC_.jpg",
    ],
    id: "34",
  },
  {
    name: "HP AERO 15 ",
    category: "Laptop",
    description:
      "Gigabyte AERO 15 OLED KD-95US66P, Intel Core i9-11980HK, 32GB DDR4, 1TB SSD, NVIDIA GeForce RTX 3080, 15.6 Inch 4K UHD OLED Display, Windows 11, Black",
    features: [
      "Processor Intel Core i9-11980HK",
      "RAM 32GB DDR4",
      "Storage 1TB SSD",
      "Graphics NVIDIA GeForce RTX 3080",
      "Display 15.6 Inch 4K UHD OLED Display",
      "Operating System Windows 11",
    ],
    price: "L.E 64999",
    colors: ["Black"],
    rating: 5,
    releasedDate: "2023-12-01",
    brand: "Gigabyte",
    images: [
      "https://m.media-amazon.com/images/I/617BBlaprcL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61B-7oqMssL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61A-xDaxKSL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71MwLHJ6BZL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/811iaYPoATL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81U5xBtyXCL._AC_SX679_.jpg",
    ],
    id: "35",
  },
  {
    name: "Dell XPS 15",
    category: "Laptop",
    description:
      "Dell XPS 15 9510, Intel Core i9-11900H, 32GB DDR4, 1TB SSD, NVIDIA GeForce RTX 3050 Ti, 15.6 Inch UHD+ Touch Display, Windows 11, Silver",
    features: [
      "Processor Intel Core i9-11900H",
      "RAM 32GB DDR4",
      "Storage 1TB SSD",
      "Graphics NVIDIA GeForce RTX 3050 Ti",
      "Display 15.6 Inch UHD+ Touch Display",
      "Operating System Windows 11",
    ],
    price: "L.E 56999",
    colors: ["Silver"],
    rating: 4.5,
    releasedDate: "2023-10-01",
    brand: "Dell",
    images: [
      "https://m.media-amazon.com/images/I/81yFhIRb8bL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71HOAOMMIfL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71f5uhyVu+L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81FPLqRBsKL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81kr+6zlYSL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71TTJyB+p9L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71HpZ5vjD0L._AC_SX679_.jpg",
    ],
    id: "36",
  },
  {
    name: "Alienware X15",
    category: "Laptop",
    description:
      "Alienware X15 R2, Intel Core i9-12900HK, 32GB DDR4, 2TB SSD, NVIDIA GeForce RTX 3080 Ti, 15.6 Inch QHD 240Hz Display, Windows 11, Lunar Light",
    features: [
      "Processor Intel Core i9-12900HK",
      "RAM 32GB DDR4",
      "Storage 2TB SSD",
      "Graphics NVIDIA GeForce RTX 3080 Ti",
      "Display 15.6 Inch QHD 240Hz Display",
      "Operating System Windows 11",
    ],
    price: "L.E 74999",
    colors: ["Lunar Light"],
    rating: 5,
    releasedDate: "2023-11-30",
    brand: "Alienware",
    images: [
      "https://m.media-amazon.com/images/I/71RbT53F8pL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/81oxUnvX9QL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71X5yd0vLaL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/5137HkQgj0L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61rQXcsudbL._AC_SX679_.jpg",
    ],
    id: "37",
  },
  {
    name: "Zenbook Pro 14",
    category: "Laptop",
    description:
      "Zenbook Pro 14 Duo 15 OLED UX582LR-XS94T, Intel Core i9-11900H, 32GB DDR4, 1TB SSD, NVIDIA GeForce RTX 3070, 15.6 Inch 4K UHD OLED Touch Display, Windows 11, Celestial Blue",
    features: [
      "Processor Intel Core i9-11900H",
      "RAM 32GB DDR4",
      "Storage 1TB SSD",
      "Graphics NVIDIA GeForce RTX 3070",
      "Display 15.6 Inch 4K UHD OLED Touch Display",
      "Operating System Windows 11",
    ],
    price: "L.E 64999",
    colors: ["Celestial Blue"],
    rating: 4.5,
    releasedDate: "2023-12-15",
    brand: "ASUS",
    images: [
      "https://m.media-amazon.com/images/I/713R3LxSt3L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71eqRUBRxaL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/812a57RHUCL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71f617oc30L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/815xlIjSVQL._AC_SX679_.jpg",
    ],
    id: "38",
  },
  {
    name: "Acer Predator Helios 300",
    category: "Laptop",
    description:
      "Acer Predator Helios 300 PH315-54-760S, Intel Core i7-11800H, 16GB DDR4, 512GB SSD, NVIDIA GeForce RTX 3060, 15.6 Inch FHD 144Hz IPS Display, Windows 11, Abyssal Black",
    features: [
      "Processor Intel Core i7-11800H",
      "RAM 16GB DDR4",
      "Storage 512GB SSD",
      "Graphics NVIDIA GeForce RTX 3060",
      "Display 15.6 Inch FHD 144Hz IPS Display",
      "Operating System Windows 11",
    ],
    price: "L.E 29999",
    colors: ["Abyssal Black"],
    rating: 4.5,
    releasedDate: "2023-11-01",
    brand: "Acer",
    images: [
      "https://m.media-amazon.com/images/I/71DhkHs4pqL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71vWKn4cCFL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/613UK03N1PL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71YV41Fky7L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71I8fbFCTtL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51dwDWGHowS._AC_SX679_.jpg",
    ],
    id: "39",
  },
  {
    name: "HP Laptop 15S-FQ5048NE",
    category: "Laptop",
    description:
      "HP Laptop 15S-FQ5048NE PH315-54-760S, Intel Core i7-11800H, 16GB DDR4, 512GB SSD, NVIDIA GeForce RTX 3060, 15.6 Inch FHD 144Hz IPS Display, Windows 11, Abyssal Black",
    features: [
      "Processor Intel Core i7-11800H",
      "RAM 16GB DDR4",
      "Storage 512GB SSD",
      "Graphics NVIDIA GeForce RTX 3060",
      "Display 15.6 Inch FHD 144Hz IPS Display",
      "Operating System Windows 11",
    ],
    price: "L.E 9999",
    colors: ["Abyssal Black"],
    rating: 4.5,
    releasedDate: "2023-11-01",
    brand: "Acer",
    images: [
      "https://m.media-amazon.com/images/I/41cB8D8IbZL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41GN+IMpBdL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41FaN4SSBxL._AC_SX679_.jpg",
    ],
    id: "40",
  },
];
