export const orders = [
  {
    orderNumber: "ORD-001",
    user: "John Doe",
    orderStatus: "Pending",
    orderDate: "2024-10-01",
    orderPrice: "$100",
  },
  {
    orderNumber: "ORD-002",
    user: "Jane Smith",
    orderStatus: "Delivered",
    orderDate: "2024-10-02",
    orderPrice: "$150",
  },
  {
    orderNumber: "ORD-003",
    user: "Michael Johnson",
    orderStatus: "Delivered",
    orderDate: "2024-10-03",
    orderPrice: "$200",
  },
  {
    orderNumber: "ORD-004",
    user: "Emily Davis",
    orderStatus: "Shipped",
    orderDate: "2024-10-04",
    orderPrice: "$250",
  },
  {
    orderNumber: "ORD-005",
    user: "David Brown",
    orderStatus: "Cancelled",
    orderDate: "2024-10-05",
    orderPrice: "$300",
  },
  {
    orderNumber: "ORD-006",
    user: "Jessica White",
    orderStatus: "Shipped",
    orderDate: "2024-10-06",
    orderPrice: "$350",
  },
  {
    orderNumber: "ORD-007",
    user: "Thomas Harris",
    orderStatus: "Delivered",
    orderDate: "2024-10-07",
    orderPrice: "$400",
  },
  {
    orderNumber: "ORD-008",
    user: "Sophia Martin",
    orderStatus: "Pending",
    orderDate: "2024-10-08",
    orderPrice: "$450",
  },
  {
    orderNumber: "ORD-009",
    user: "Daniel Thompson",
    orderStatus: "Cancelled",
    orderDate: "2024-10-09",
    orderPrice: "$500",
  },
  {
    orderNumber: "ORD-010",
    user: "Emma Garcia",
    orderStatus: "Shipped",
    orderDate: "2024-10-10",
    orderPrice: "$550",
  },
  {
    orderNumber: "ORD-011",
    user: "Matthew Martinez",
    orderStatus: "Delivered",
    orderDate: "2024-10-11",
    orderPrice: "$600",
  },
  {
    orderNumber: "ORD-012",
    user: "Ava Robinson",
    orderStatus: "Pending",
    orderDate: "2024-10-12",
    orderPrice: "$650",
  },
  {
    orderNumber: "ORD-013",
    user: "Isabella Clark",
    orderStatus: "Cancelled",
    orderDate: "2024-10-13",
    orderPrice: "$700",
  },
  {
    orderNumber: "ORD-014",
    user: "James Lewis",
    orderStatus: "Shipped",
    orderDate: "2024-10-14",
    orderPrice: "$750",
  },
  {
    orderNumber: "ORD-015",
    user: "Benjamin Walker",
    orderStatus: "Delivered",
    orderDate: "2024-10-15",
    orderPrice: "$800",
  },
  {
    orderNumber: "ORD-016",
    user: "Charlotte Hall",
    orderStatus: "Pending",
    orderDate: "2024-10-16",
    orderPrice: "$850",
  },
  {
    orderNumber: "ORD-017",
    user: "Oliver Allen",
    orderStatus: "Cancelled",
    orderDate: "2024-10-17",
    orderPrice: "$900",
  },
  {
    orderNumber: "ORD-018",
    user: "Liam Young",
    orderStatus: "Shipped",
    orderDate: "2024-10-18",
    orderPrice: "$950",
  },
  {
    orderNumber: "ORD-019",
    user: "Mia Hernandez",
    orderStatus: "Delivered",
    orderDate: "2024-10-19",
    orderPrice: "$1000",
  },
  {
    orderNumber: "ORD-020",
    user: "Noah King",
    orderStatus: "Pending",
    orderDate: "2024-10-20",
    orderPrice: "$1050",
  },
];
