export const recentOrders = [
  { name: "Ahmed Ibrahim", color: "orange", money: 1200 },
  { name: "Sarah Al-Jaberi", color: "red", money: 1500 },
  { name: "Mohamed Ali", color: "blue", money: 2000 },
  { name: "Fatima Khalid", color: "green", money: 950 },
  { name: "Yousef Saeed", color: "grey", money: 1750 },
  { name: "Layla Hasan", color: "purple", money: 1800 },
  { name: "Kareem Saeed", color: "pink", money: 1250 },
  { name: "Mona Al-Hussein", color: "teal", money: 1100 },
  { name: "Ayman Ibrahim", color: "indigo", money: 2300 },
  { name: "Zahra Abbas", color: "brown", money: 1900 },
  { name: "Hani Al-Bashir", color: "grey", money: 1350 },
  { name: "Noura Fahd", color: "cyan", money: 1420 },
  { name: "Ali Mansour", color: "lime", money: 1680 },
  { name: "Salma Al-Faraj", color: "amber", money: 1520 },
  { name: "Omar Ismail", color: "fuchsia", money: 2100 },
];
