export const users = [
  { name: "Ahmed Ali", isAdmin: true },
  { name: "Mohamed Ibrahim", isAdmin: false },
  { name: "Fatma Abdelrahman", isAdmin: false },
  { name: "Salah El-Sayed", isAdmin: true },
  { name: "Khaled Mostafa", isAdmin: false },
  { name: "Youssef Hassan", isAdmin: false },
  { name: "Mahmoud Ismail", isAdmin: false },
  { name: "Amina Khalil", isAdmin: false },
  { name: "Hana Ahmed", isAdmin: false },
  { name: "Omar Alaa", isAdmin: false },
  { name: "Sara Adel", isAdmin: false },
  { name: "Hussein Ali", isAdmin: false },
  { name: "Laila Ezzat", isAdmin: false },
  { name: "Zainab Mahmoud", isAdmin: false },
  { name: "Nadine Saeed", isAdmin: false },
  { name: "Mona Hamed", isAdmin: false },
  { name: "Adel Ahmed", isAdmin: false },
  { name: "Rania Mohamed", isAdmin: false },
  { name: "Moustafa Hassan", isAdmin: false },
  { name: "Asmaa El-Sayed", isAdmin: false },
];
