export const data = [
  {
    name: "iPhone 14 Pro",
    category: "Smartphone",
    description:
      "Apple's latest flagship smartphone with advanced camera and display technology.",
    features: [
      "6.7-inch Super Retina XDR display",
      "Triple-camera system with LiDAR scanner",
      "5G connectivity",
      "A16 Bionic chip",
      "ProMotion technology",
      "iOS 16",
    ],
    price: "$1099",
    colors: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    rating: 4,
    releasedDate: "2022-09-30",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/717trh2j6CL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41+DC2aGiuL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg",
    ],
    id: "1",
  },
  {
    name: "iPhone 13 Mini",
    category: "Smartphone",
    description:
      "Compact flagship iPhone with powerful features in a small size.",
    features: [
      "5.4-inch Super Retina XDR display",
      "Dual-camera system",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$699",
    colors: ["Pink", "Blue", "Midnight", "Starlight", "Product(RED)"],
    rating: 4,
    releasedDate: "2021-09-24",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/51yG1FjZVYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Z4qLSOGhL._AC_SL1200_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-mini-01.jpg",
    ],
    id: "2",
  },
  {
    name: "iPhone SE (2022)",
    category: "Smartphone",
    description: "Affordable iPhone with A15 chip and 5G capability.",
    features: [
      "4.7-inch Retina HD display",
      "Single 12MP wide camera",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$429",
    colors: ["Midnight", "Starlight", "Product(RED)"],
    rating: 3.5,
    releasedDate: "2022-03-18",
    brand: "Apple",
    images: [
      "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022.jpg",
      "https://cdn.shortpixel.ai/spai/w_375+q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022-colors.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/apple-iphone-se-2020/lifestyle/-1024w2/gsmarena_009.jpg",
    ],
    id: "3",
  },
  {
    name: "iPhone 12",
    category: "Smartphone",
    description: "Powerful and iconic smartphone with impressive technology.",
    features: [
      "6.1-inch Super Retina XDR display",
      "Dual-camera system",
      "A14 Bionic chip",
      "iOS 14",
      "5G connectivity",
    ],
    price: "$799",
    colors: ["Black", "White", "Red", "Green", "Blue"],
    rating: 4.5,
    releasedDate: "2020-10-23",
    brand: "Apple",
    images: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg",
      "https://m.media-amazon.com/images/I/71UlOmYIClL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg",
    ],
    id: "4",
  },
  {
    name: "iPhone 14 Pro",
    category: "Smartphone",
    description:
      "Apple's latest flagship smartphone with advanced camera and display technology.",
    features: [
      "6.7-inch Super Retina XDR display",
      "Triple-camera system with LiDAR scanner",
      "5G connectivity",
      "A16 Bionic chip",
      "ProMotion technology",
      "iOS 16",
    ],
    price: "$1099",
    colors: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    rating: 4,
    releasedDate: "2022-09-30",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/717trh2j6CL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41+DC2aGiuL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg",
    ],
    id: "1",
  },
  {
    name: "iPhone 13 Mini",
    category: "Smartphone",
    description:
      "Compact flagship iPhone with powerful features in a small size.",
    features: [
      "5.4-inch Super Retina XDR display",
      "Dual-camera system",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$699",
    colors: ["Pink", "Blue", "Midnight", "Starlight", "Product(RED)"],
    rating: 4,
    releasedDate: "2021-09-24",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/51yG1FjZVYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Z4qLSOGhL._AC_SL1200_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-mini-01.jpg",
    ],
    id: "2",
  },
  {
    name: "iPhone SE (2022)",
    category: "Smartphone",
    description: "Affordable iPhone with A15 chip and 5G capability.",
    features: [
      "4.7-inch Retina HD display",
      "Single 12MP wide camera",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$429",
    colors: ["Midnight", "Starlight", "Product(RED)"],
    rating: 3.5,
    releasedDate: "2022-03-18",
    brand: "Apple",
    images: [
      "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022.jpg",
      "https://cdn.shortpixel.ai/spai/w_375+q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022-colors.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/apple-iphone-se-2020/lifestyle/-1024w2/gsmarena_009.jpg",
    ],
    id: "3",
  },
  {
    name: "iPhone 12",
    category: "Smartphone",
    description: "Powerful and iconic smartphone with impressive technology.",
    features: [
      "6.1-inch Super Retina XDR display",
      "Dual-camera system",
      "A14 Bionic chip",
      "iOS 14",
      "5G connectivity",
    ],
    price: "$799",
    colors: ["Black", "White", "Red", "Green", "Blue"],
    rating: 4.5,
    releasedDate: "2020-10-23",
    brand: "Apple",
    images: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg",
      "https://m.media-amazon.com/images/I/71UlOmYIClL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg",
    ],
    id: "4",
  },
  {
    name: "iPhone 14 Pro",
    category: "Smartphone",
    description:
      "Apple's latest flagship smartphone with advanced camera and display technology.",
    features: [
      "6.7-inch Super Retina XDR display",
      "Triple-camera system with LiDAR scanner",
      "5G connectivity",
      "A16 Bionic chip",
      "ProMotion technology",
      "iOS 16",
    ],
    price: "$1099",
    colors: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    rating: 4,
    releasedDate: "2022-09-30",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/717trh2j6CL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41+DC2aGiuL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg",
    ],
    id: "1",
  },
  {
    name: "iPhone 13 Mini",
    category: "Smartphone",
    description:
      "Compact flagship iPhone with powerful features in a small size.",
    features: [
      "5.4-inch Super Retina XDR display",
      "Dual-camera system",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$699",
    colors: ["Pink", "Blue", "Midnight", "Starlight", "Product(RED)"],
    rating: 4,
    releasedDate: "2021-09-24",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/51yG1FjZVYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Z4qLSOGhL._AC_SL1200_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-mini-01.jpg",
    ],
    id: "2",
  },
  {
    name: "iPhone SE (2022)",
    category: "Smartphone",
    description: "Affordable iPhone with A15 chip and 5G capability.",
    features: [
      "4.7-inch Retina HD display",
      "Single 12MP wide camera",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$429",
    colors: ["Midnight", "Starlight", "Product(RED)"],
    rating: 3.5,
    releasedDate: "2022-03-18",
    brand: "Apple",
    images: [
      "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022.jpg",
      "https://cdn.shortpixel.ai/spai/w_375+q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022-colors.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/apple-iphone-se-2020/lifestyle/-1024w2/gsmarena_009.jpg",
    ],
    id: "3",
  },
  {
    name: "iPhone 12",
    category: "Smartphone",
    description: "Powerful and iconic smartphone with impressive technology.",
    features: [
      "6.1-inch Super Retina XDR display",
      "Dual-camera system",
      "A14 Bionic chip",
      "iOS 14",
      "5G connectivity",
    ],
    price: "$799",
    colors: ["Black", "White", "Red", "Green", "Blue"],
    rating: 4.5,
    releasedDate: "2020-10-23",
    brand: "Apple",
    images: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg",
      "https://m.media-amazon.com/images/I/71UlOmYIClL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg",
    ],
    id: "4",
  },
  {
    name: "iPhone 14 Pro",
    category: "Smartphone",
    description:
      "Apple's latest flagship smartphone with advanced camera and display technology.",
    features: [
      "6.7-inch Super Retina XDR display",
      "Triple-camera system with LiDAR scanner",
      "5G connectivity",
      "A16 Bionic chip",
      "ProMotion technology",
      "iOS 16",
    ],
    price: "$1099",
    colors: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    rating: 4,
    releasedDate: "2022-09-30",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/717trh2j6CL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41+DC2aGiuL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg",
    ],
    id: "1",
  },
  {
    name: "iPhone 13 Mini",
    category: "Smartphone",
    description:
      "Compact flagship iPhone with powerful features in a small size.",
    features: [
      "5.4-inch Super Retina XDR display",
      "Dual-camera system",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$699",
    colors: ["Pink", "Blue", "Midnight", "Starlight", "Product(RED)"],
    rating: 4,
    releasedDate: "2021-09-24",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/51yG1FjZVYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Z4qLSOGhL._AC_SL1200_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-mini-01.jpg",
    ],
    id: "2",
  },
  {
    name: "iPhone SE (2022)",
    category: "Smartphone",
    description: "Affordable iPhone with A15 chip and 5G capability.",
    features: [
      "4.7-inch Retina HD display",
      "Single 12MP wide camera",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$429",
    colors: ["Midnight", "Starlight", "Product(RED)"],
    rating: 3.5,
    releasedDate: "2022-03-18",
    brand: "Apple",
    images: [
      "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022.jpg",
      "https://cdn.shortpixel.ai/spai/w_375+q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022-colors.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/apple-iphone-se-2020/lifestyle/-1024w2/gsmarena_009.jpg",
    ],
    id: "3",
  },
  {
    name: "iPhone 12",
    category: "Smartphone",
    description: "Powerful and iconic smartphone with impressive technology.",
    features: [
      "6.1-inch Super Retina XDR display",
      "Dual-camera system",
      "A14 Bionic chip",
      "iOS 14",
      "5G connectivity",
    ],
    price: "$799",
    colors: ["Black", "White", "Red", "Green", "Blue"],
    rating: 4.5,
    releasedDate: "2020-10-23",
    brand: "Apple",
    images: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg",
      "https://m.media-amazon.com/images/I/71UlOmYIClL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg",
    ],
    id: "4",
  },
  {
    name: "iPhone 14 Pro",
    category: "Smartphone",
    description:
      "Apple's latest flagship smartphone with advanced camera and display technology.",
    features: [
      "6.7-inch Super Retina XDR display",
      "Triple-camera system with LiDAR scanner",
      "5G connectivity",
      "A16 Bionic chip",
      "ProMotion technology",
      "iOS 16",
    ],
    price: "$1099",
    colors: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    rating: 4,
    releasedDate: "2022-09-30",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/717trh2j6CL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41+DC2aGiuL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg",
    ],
    id: "1",
  },
  {
    name: "iPhone 13 Mini",
    category: "Smartphone",
    description:
      "Compact flagship iPhone with powerful features in a small size.",
    features: [
      "5.4-inch Super Retina XDR display",
      "Dual-camera system",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$699",
    colors: ["Pink", "Blue", "Midnight", "Starlight", "Product(RED)"],
    rating: 4,
    releasedDate: "2021-09-24",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/51yG1FjZVYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Z4qLSOGhL._AC_SL1200_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-mini-01.jpg",
    ],
    id: "2",
  },
  {
    name: "iPhone SE (2022)",
    category: "Smartphone",
    description: "Affordable iPhone with A15 chip and 5G capability.",
    features: [
      "4.7-inch Retina HD display",
      "Single 12MP wide camera",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$429",
    colors: ["Midnight", "Starlight", "Product(RED)"],
    rating: 3.5,
    releasedDate: "2022-03-18",
    brand: "Apple",
    images: [
      "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022.jpg",
      "https://cdn.shortpixel.ai/spai/w_375+q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022-colors.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/apple-iphone-se-2020/lifestyle/-1024w2/gsmarena_009.jpg",
    ],
    id: "3",
  },
  {
    name: "iPhone 12",
    category: "Smartphone",
    description: "Powerful and iconic smartphone with impressive technology.",
    features: [
      "6.1-inch Super Retina XDR display",
      "Dual-camera system",
      "A14 Bionic chip",
      "iOS 14",
      "5G connectivity",
    ],
    price: "$799",
    colors: ["Black", "White", "Red", "Green", "Blue"],
    rating: 4.5,
    releasedDate: "2020-10-23",
    brand: "Apple",
    images: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg",
      "https://m.media-amazon.com/images/I/71UlOmYIClL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg",
    ],
    id: "4",
  },
  {
    name: "iPhone 14 Pro",
    category: "Smartphone",
    description:
      "Apple's latest flagship smartphone with advanced camera and display technology.",
    features: [
      "6.7-inch Super Retina XDR display",
      "Triple-camera system with LiDAR scanner",
      "5G connectivity",
      "A16 Bionic chip",
      "ProMotion technology",
      "iOS 16",
    ],
    price: "$1099",
    colors: ["Graphite", "Gold", "Silver", "Sierra Blue"],
    rating: 4,
    releasedDate: "2022-09-30",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/717trh2j6CL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41+DC2aGiuL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg",
    ],
    id: "1",
  },
  {
    name: "iPhone 13 Mini",
    category: "Smartphone",
    description:
      "Compact flagship iPhone with powerful features in a small size.",
    features: [
      "5.4-inch Super Retina XDR display",
      "Dual-camera system",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$699",
    colors: ["Pink", "Blue", "Midnight", "Starlight", "Product(RED)"],
    rating: 4,
    releasedDate: "2021-09-24",
    brand: "Apple",
    images: [
      "https://m.media-amazon.com/images/I/51yG1FjZVYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Z4qLSOGhL._AC_SL1200_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-mini-01.jpg",
    ],
    id: "2",
  },
  {
    name: "iPhone SE (2022)",
    category: "Smartphone",
    description: "Affordable iPhone with A15 chip and 5G capability.",
    features: [
      "4.7-inch Retina HD display",
      "Single 12MP wide camera",
      "A15 Bionic chip",
      "iOS 15",
      "5G connectivity",
    ],
    price: "$429",
    colors: ["Midnight", "Starlight", "Product(RED)"],
    rating: 3.5,
    releasedDate: "2022-03-18",
    brand: "Apple",
    images: [
      "https://cdn.shortpixel.ai/spai/q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022.jpg",
      "https://cdn.shortpixel.ai/spai/w_375+q_glossy+ret_img+to_webp/mobizil.com/wp-content/uploads/2022/03/Apple-iPhone-SE-2022-colors.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/apple-iphone-se-2020/lifestyle/-1024w2/gsmarena_009.jpg",
    ],
    id: "3",
  },
  {
    name: "iPhone 12",
    category: "Smartphone",
    description: "Powerful and iconic smartphone with impressive technology.",
    features: [
      "6.1-inch Super Retina XDR display",
      "Dual-camera system",
      "A14 Bionic chip",
      "iOS 14",
      "5G connectivity",
    ],
    price: "$799",
    colors: ["Black", "White", "Red", "Green", "Blue"],
    rating: 4.5,
    releasedDate: "2020-10-23",
    brand: "Apple",
    images: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg",
      "https://m.media-amazon.com/images/I/71UlOmYIClL._AC_SL1500_.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-2.jpg",
    ],
    id: "4",
  },
];
